### ISSUE TITLE
Tests do not pass on master

### ISSUE THREAD

**Issue by retr0h** [FriendCode/giturlparse.py#14]
Tests do not pass on master.

```
$ python -m giturlparse.tests
testInvalidUrls (giturlparse.tests.parse.UrlParseTestCase) ... ok
testValidUrls (giturlparse.tests.parse.UrlParseTestCase) ... FAIL
testRewrites (giturlparse.tests.rewrite.UrlRewriteTestCase) ... FAIL

======================================================================
FAIL: testValidUrls (giturlparse.tests.parse.UrlParseTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "giturlparse/tests/parse.py", line 112, in testValidUrls
    self._test_valid(*data)
  File "giturlparse/tests/parse.py", line 108, in _test_valid
    self.assertEqual(attr_v, v, "[%s] Property '%s' should be '%s' but is '%s'" % (url, k, attr_v, v))
AssertionError: [git@host.org:9999/Org/Repo.git] Property 'owner' should be '9999/Org' but is 'Org'

======================================================================
FAIL: testRewrites (giturlparse.tests.rewrite.UrlRewriteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "giturlparse/tests/rewrite.py", line 71, in testRewrites
    self._test_rewrite(*data)
  File "giturlparse/tests/rewrite.py", line 66, in _test_rewrite
    return self.assertEqual(parse(source).format(protocol), dest)
AssertionError: 'git@host.org:Org/Repo.git' != 'ssh://git@host.org:Org/Repo.git'

----------------------------------------------------------------------
Ran 3 tests in 0.002s

FAILED (failures=2)

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by retr0h** [comment]
Closing.  Implemented a crude [git-url-parse](https://github.com/retr0h/git-url-parse) maintained by myself.
